wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.34.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743738142.54315
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 66
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 66
      - 71
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.15.12
      6: 4.34.1
      8:
      - 5
      13: linux-x86_64
num_nodes:
  desc: null
  value: 1
num_gpus_per_node:
  desc: null
  value: 1
node_name:
  desc: null
  value: unknown because NODENAME environment variable not set
rank_zero_seed:
  desc: null
  value: 17
